build:
  maxIssues: 0

complexity:
  LongMethod:
    active: true
    threshold: 90
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 8
  TooManyFunctions:
    active: true
    thresholdInFiles: 20
    thresholdInClasses: 15
    thresholdInInterfaces: 15
    thresholdInObjects: 20
    thresholdInEnums: 15

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - Composable
      - Preview
  MatchingDeclarationName:
    active: true

exceptions:
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - e
      - expected
      - ignored
      - _:ignored

empty-blocks:
  EmptyCatchBlock:
    active: true

style:
  MaxLineLength:
    active: false
  NewLineAtEndOfFile:
    active: false
  ReturnCount:
    active: true
    max: 4
  UnusedPrivateMember:
    active: true
    ignoreAnnotated:
      - Preview
  UnusedParameter:
    active: true

  MagicNumber:
    active: true
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '10'
      - '100'
      - '200'
      - '299'
      - '300'
      - '399'
      - '2048'
      - '4096'
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  WildcardImport:
    active: true
